# pyproject.toml
[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.0"
uvicorn = { extras = ["standard"], version = "^0.23.0" }
pydantic = "^2.0"
transformers = "^4.0"
# (plus any of your adapter’s deps: torch, sentencepiece, mistral-inference, etc)
httpx = "^0.27.0"