# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: implicitus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'implicitus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10implicitus.proto\x12\nimplicitus\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"(\n\x03\x42ox\x12!\n\x04size\x18\x01 \x01(\x0b\x32\x13.implicitus.Vector3\"\x18\n\x06Sphere\x12\x0e\n\x06radius\x18\x01 \x01(\x01\"*\n\x08\x43ylinder\x12\x0e\n\x06radius\x18\x01 \x01(\x01\x12\x0e\n\x06height\x18\x02 \x01(\x01\"\x84\x01\n\tPrimitive\x12\x1e\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x0f.implicitus.BoxH\x00\x12$\n\x06sphere\x18\x02 \x01(\x0b\x32\x12.implicitus.SphereH\x00\x12(\n\x08\x63ylinder\x18\x03 \x01(\x0b\x32\x14.implicitus.CylinderH\x00\x42\x07\n\x05shape\"0\n\tTranslate\x12#\n\x06offset\x18\x01 \x01(\x0b\x32\x13.implicitus.Vector3\"-\n\x05Scale\x12$\n\x07\x66\x61\x63tors\x18\x01 \x01(\x0b\x32\x13.implicitus.Vector3\"a\n\tTransform\x12*\n\ttranslate\x18\x01 \x01(\x0b\x32\x15.implicitus.TranslateH\x00\x12\"\n\x05scale\x18\x02 \x01(\x0b\x32\x11.implicitus.ScaleH\x00\x42\x04\n\x02op\"\x8a\x01\n\x04Node\x12*\n\tprimitive\x18\x01 \x01(\x0b\x32\x15.implicitus.PrimitiveH\x00\x12*\n\ttransform\x18\x02 \x01(\x0b\x32\x15.implicitus.TransformH\x00\x12\"\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x10.implicitus.NodeB\x06\n\x04\x62ody\"3\n\x05Model\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x04root\x18\x02 \x01(\x0b\x32\x10.implicitus.Nodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'implicitus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3']._serialized_start=32
  _globals['_VECTOR3']._serialized_end=74
  _globals['_BOX']._serialized_start=76
  _globals['_BOX']._serialized_end=116
  _globals['_SPHERE']._serialized_start=118
  _globals['_SPHERE']._serialized_end=142
  _globals['_CYLINDER']._serialized_start=144
  _globals['_CYLINDER']._serialized_end=186
  _globals['_PRIMITIVE']._serialized_start=189
  _globals['_PRIMITIVE']._serialized_end=321
  _globals['_TRANSLATE']._serialized_start=323
  _globals['_TRANSLATE']._serialized_end=371
  _globals['_SCALE']._serialized_start=373
  _globals['_SCALE']._serialized_end=418
  _globals['_TRANSFORM']._serialized_start=420
  _globals['_TRANSFORM']._serialized_end=517
  _globals['_NODE']._serialized_start=520
  _globals['_NODE']._serialized_end=658
  _globals['_MODEL']._serialized_start=660
  _globals['_MODEL']._serialized_end=711
# @@protoc_insertion_point(module_scope)
